from typing import Protocol
from uuid import UUID

from .schemas import (
    BedCreate,
    BedRead,
    BedUpdate,
    BuildingCreate,
    BuildingRead,
    BuildingUpdate,
    RoomCreate,
    RoomMatrixBuilding,
    RoomRead,
    RoomTypeCreate,
    RoomTypeRead,
    RoomTypeUpdate,
    RoomUpdate,
)


class HousingRepository(Protocol):
    def list_buildings(self) -> list[BuildingRead]: ...
    def get_building(self, item_id: UUID) -> BuildingRead | None: ...
    def create_building(self, data: BuildingCreate) -> BuildingRead: ...
    def update_building(self, item_id: UUID, data: BuildingUpdate) -> BuildingRead | None: ...
    def delete_building(self, item_id: UUID) -> bool: ...
    def list_room_types(self) -> list[RoomTypeRead]: ...
    def create_room_type(self, data: RoomTypeCreate) -> RoomTypeRead: ...
    def update_room_type(self, item_id: UUID, data: RoomTypeUpdate) -> RoomTypeRead | None: ...
    def delete_room_type(self, item_id: UUID) -> bool: ...
    def list_rooms(self, building_id: UUID | None = None) -> list[RoomRead]: ...
    def create_room(self, data: RoomCreate) -> RoomRead: ...
    def update_room(self, item_id: UUID, data: RoomUpdate) -> RoomRead | None: ...
    def delete_room(self, item_id: UUID) -> bool: ...
    def list_beds(self, room_id: UUID | None = None) -> list[BedRead]: ...
    def create_bed(self, data: BedCreate) -> BedRead: ...
    def update_bed(self, item_id: UUID, data: BedUpdate) -> BedRead | None: ...
    def delete_bed(self, item_id: UUID) -> bool: ...
    def room_matrix(self) -> list[RoomMatrixBuilding]: ...
